### ISSUE TITLE
PATH Error

### ISSUE THREAD

**Issue by mugukamil** [sapegin/dotfiles#3]
hey, I have PATH error can u help me?

![screenshot 2016-01-11 09 30 31](https://cloud.githubusercontent.com/assets/4193470/12227982/13d2fd40-b846-11e5-8c50-85f0f1d61662.png)
![screenshot 2016-01-11 09 31 44](https://cloud.githubusercontent.com/assets/4193470/12227994/2834354c-b846-11e5-99f4-d90b1cc8f7bd.png)

![screenshot 2016-01-11 09 30 55](https://cloud.githubusercontent.com/assets/4193470/12227983/13d65fee-b846-11e5-8b8f-e7b6c54c770f.png)

**Comment by sapegin** [comment]
Obviously you have no node installed. To print a variable you should do `echo $PATH`.

**Comment by mugukamil** [comment]
че я на анг пишу)).     да действительно нода куда-то пропала, установил заного все гуд.
